version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      day: monday
      time: "06:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      actions:
        update-types:
          - minor
          - patch
