version = 1

auto_approve_usernames = ["renovate", "dependabot", "dependabot[bot]"]

[merge]
method = "squash"
require_automerge_checkpoint = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["renovate", "dependabot", "dependabot[bot]"]

[merge.automerge]
title = "{{{title}}} (automerge)"

[update]
always = true
automerge_title = true
ignored_usernames = ["renovate"]

[plan]
require_automerge = true
