packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@hookform/resolvers'
  - 'lucide-react'
  - 'react-hook-form'
  - '@types/pg'

overrides:
  next>postcss: ^8.5.18
  next>sharp: ^0.35.0
